In [1]:
import numpy as np


In [2]:
print(np.__version__)
np.show_config()

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z=np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
Z=np.arange(50)
Z=Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [10]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int32),)

In [12]:
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
z=np.random.random((3,3,3))
z

array([[[0.3377169 , 0.56463887, 0.96046279],
        [0.78354642, 0.22259613, 0.45622933],
        [0.49026729, 0.82800853, 0.91704436]],

       [[0.46430855, 0.36939432, 0.61527947],
        [0.93663868, 0.4118337 , 0.0841565 ],
        [0.08183987, 0.68028838, 0.61584277]],

       [[0.48220284, 0.80536729, 0.83139714],
        [0.42434985, 0.3865013 , 0.30463815],
        [0.14796958, 0.80776669, 0.976891  ]]])

In [24]:
z=np.random.random((10,10))
print(z)
zmin=z.min()
zmax=z.max()
print(zmin,zmax)

[[0.95316884 0.39183136 0.48821225 0.51959657 0.82687647 0.41196862
  0.32328933 0.29266304 0.3020434  0.05957147]
 [0.35148582 0.4001634  0.66669282 0.91996467 0.17547812 0.94577808
  0.26273848 0.16936258 0.23639935 0.10552674]
 [0.90630978 0.99438497 0.49631511 0.17863615 0.10810134 0.7640007
  0.9717351  0.82066784 0.20012111 0.15338858]
 [0.80274423 0.04479385 0.87776508 0.1680474  0.68362292 0.9374748
  0.35922524 0.5879776  0.16934822 0.1015305 ]
 [0.59155543 0.18430302 0.49103462 0.00455363 0.25253925 0.02856172
  0.04380046 0.85399368 0.34648795 0.00315204]
 [0.95249838 0.64287635 0.99284749 0.32622118 0.20231841 0.21856634
  0.09119731 0.75825495 0.88499011 0.91156679]
 [0.13830478 0.64040141 0.47568676 0.78255614 0.31772835 0.65433827
  0.79450466 0.53367532 0.03108405 0.99367196]
 [0.6995712  0.13682697 0.19877596 0.84916913 0.07712543 0.80024976
  0.24713014 0.49745382 0.23230789 0.61098123]
 [0.1555061  0.55376141 0.75849188 0.6448707  0.96016152 0.75777713
  0.19340601 0

In [26]:
z=np.random.random(30)
print(z)
m=z.mean()
print(m)

[0.13110771 0.33974515 0.549928   0.91637272 0.51547669 0.96719204
 0.15232151 0.16112149 0.45145973 0.03154847 0.00397039 0.9550375
 0.7753755  0.18938326 0.45549306 0.75019601 0.8960432  0.2855428
 0.7447632  0.4215945  0.18899177 0.71357293 0.30740889 0.42357671
 0.93091502 0.70709095 0.01722069 0.95159591 0.03752225 0.4937348 ]
0.48217676155401357


In [27]:
o=np.ones((10,10))
o[1:-1,1:-1]=0
print(o)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [33]:
0 * np.nan
np.nan=np.nan
np.inf >np.nan
print(np.nan-np.nan)
0.3==3 * 0.1

nan


False

In [41]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [55]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [56]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [65]:
Z = np.tile( np.array([[0,1],[1,0]]),(4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [67]:
Z = np.random.random((5,5))
print(Z)
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.43673498 0.12765498 0.60723397 0.41445774 0.12866115]
 [0.14330297 0.84676979 0.99336511 0.35065176 0.97351026]
 [0.26981002 0.50652446 0.37633174 0.06614118 0.56238183]
 [0.50229376 0.01442008 0.30611938 0.60116722 0.99655315]
 [0.06461374 0.59522276 0.41795735 0.91736923 0.84465301]]
[[0.42999764 0.11529487 0.60359833 0.40731513 0.11631934]
 [0.13122752 0.84749179 0.99675396 0.3423484  0.97653792]
 [0.26003598 0.50105673 0.36849555 0.05266201 0.55793026]
 [0.49674906 0.         0.29700588 0.59742122 1.        ]
 [0.05110679 0.59136862 0.41087841 0.91937557 0.8453365 ]]


In [70]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [71]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [73]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [74]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


In [75]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


ValueError: Integers to negative integer powers are not allowed.

In [76]:
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)

C:\Users\skira\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.
C:\Users\skira\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in floor_divide
  
C:\Users\skira\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\skira\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


nan

In [82]:
python.getcwd

NameError: name 'python' is not defined

In [85]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.trunc(Z + np.copysign(0.5, Z)))


[ 6.23895746 -6.80468358 -8.02983792  5.92286567 -5.61526093  0.50786871
 -6.35097422 -3.24440128 -8.37419269  0.33676417]
[ 6. -7. -8.  6. -6.  1. -6. -3. -8.  0.]


In [88]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z%1)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))


[0.19145189 5.47735366 9.67834505 6.85804364 9.96081219 0.73353703
 1.64305072 8.75709857 0.30530281 9.71663371]
[0.19145189 0.47735366 0.67834505 0.85804364 0.96081219 0.73353703
 0.64305072 0.75709857 0.30530281 0.71663371]
[0. 5. 9. 6. 9. 0. 1. 8. 0. 9.]
[0. 5. 9. 6. 9. 0. 1. 8. 0. 9.]
[0. 5. 9. 6. 9. 0. 1. 8. 0. 9.]
[0 5 9 6 9 0 1 8 0 9]
[0. 5. 9. 6. 9. 0. 1. 8. 0. 9.]


In [89]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [93]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [94]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [95]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.2177624  0.22245493 0.38291155 0.40884779 0.43306319 0.43591091
 0.4752597  0.49238701 0.8173971  0.8662757 ]


In [96]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [97]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)


False


In [98]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [102]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.09399781 0.31709081 0.82340406 0.80289234 1.06888446 0.28457034
 1.12558422 0.78575133 1.40205878 0.94042248]
[0.98007204 1.27566381 0.8333473  0.45622951 0.5719422  0.30316493
 0.83274277 0.57086828 0.78539066 0.79403714]


In [101]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.58323929 0.45234126 0.70856094 0.03582077 0.         0.26115292
 0.7134919  0.83200415 0.91739227 0.71477177]
