In [2]:
import tensorflow as tf
a=tf.constant(5.0)
b=tf.constant(6.0)
c=a*b
sess=tf.Session()
output_c=sess.run(c)
print(output_c)
sess.close()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [2]:
sess=tf.Session()
a=tf.placeholder(tf.int32)
b=tf.placeholder(tf.int32)
c=a+b
output_c=sess.run(c,feed_dict={a:5,b:6})
print(output_c)
sess.close()

11


In [3]:
sess=tf.Session()
a=tf.Variable(5,tf.int32)
b=tf.Variable(6,tf.int32)
c=a+b
init = tf.global_variables_initializer()
output_c=sess.run(init)
print("Sum =", sess.run(c))
sess.close()

Sum = 11


In [4]:
x=tf.constant(5)
y=tf.placeholder(tf.int32,name='y')
z=tf.Variable(6,tf.int32,name='z')
c=x*y*z
sess=tf.Session()
init = tf.global_variables_initializer()
output_c=sess.run(init)
print("Sum =", sess.run(c,feed_dict={y:5}))
sess.close()

Sum = 150


In [5]:
mat=tf.zeros((4,4),dtype=tf.dtypes.float32,name=None)
print(tf.print(mat))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
None


In [6]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

product = tf.matmul(matrix1, matrix2)
with tf.Session() as sess:
    result = sess.run(product)
    print(matrix1,matrix2,result)
    # ==> [[ 12.]]

AttributeError: module 'tensorflow' has no attribute 'Session'

In [7]:
import numpy as np
mat=tf.constant(np.random.random((4,4)))
print(mat)

Tensor("Const_5:0", shape=(4, 4), dtype=float64)


In [8]:
np.random.random((4,4))

array([[0.91050902, 0.02752095, 0.04044144, 0.62512701],
       [0.52538447, 0.69900298, 0.01557146, 0.20192315],
       [0.87184416, 0.74055044, 0.06018278, 0.53043544],
       [0.41306168, 0.61282716, 0.70613997, 0.35565688]])

In [ ]:
zeros = tf.zeros(my_matrix.shape(4,4))


In [ ]:
mat=tf.random.normal((4,4),mean=0.0,stddev=1.0,dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
mat

In [ ]:
mat=tf.random.uniform(
    (4,4),
    minval=0,
    maxval=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(mat)

In [ ]:
lst=tf.linspace(
    0.0,
    10.0,
    1,
    name=None
)


In [ ]:
def get_plot_buf(self):
    plt.figure()
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    plt.close()
    buf.seek(0)
    return buf
import matplotlib as mpl
mpl.use('Agg')  # No display
import matplotlib.pyplot as plt
plot_buf_ph = tf.placeholder(tf.string)
image = tf.image.decode_png(plot_buf_ph, channels=4)
image = tf.expand_dims(image, 0)
plot_image_summary = tf.summary.image('some_name', image, max_outputs=1)

plot_buf = get_plot_buf()
plot_image_summary_ = session.run(
        plot_image_summary,
        feed_dict={plot_buf_ph: plot_buf.getvalue()})
summary_writer.add_summary(plot_image_summary_, global_step=iteration)
