In [8]:
import numpy as np

In [9]:
P=np.array([[0.6,0.6,0.8,0.9],[0.1,0.2,0.9,0.8],[0.9,0.3,0.4,0.8],[0.9,0.8,0.1,0.2]])

In [10]:
Q=np.array([[0.1,0.2,0.7,0.9],[1,1,0.4,0.6],[0,0,0.5,0.9],[0.9,1,0.8,0.2]])

In [11]:
Z=np.transpose(Q)

In [10]:
ans=[]
final=[]
for i in P:
    for j in Z:
        ans.append(max(np.minimum(i,j)))
final=np.array(ans)
f=final.reshape(4,4)
print(f)

[[0.9 0.9 0.8 0.8]
 [0.8 0.8 0.8 0.9]
 [0.8 0.8 0.8 0.9]
 [0.8 0.8 0.7 0.9]]


In [11]:
ans1=[]
final1=[]
for i in P:
    for j in Z:
        ans1.append(max(np.multiply(i,j)))

final1=np.array(ans1)
f1=final1.reshape(4,4)
print(f1)

            

[[0.81 0.9  0.72 0.72]
 [0.72 0.8  0.64 0.81]
 [0.72 0.8  0.64 0.81]
 [0.8  0.8  0.63 0.81]]
